/* Словарная база: ~1380 слов, 4 уровня по частотности.
   Формат: "english|перевод" */
window.WORD_LEVELS = [
{ name: "Уровень 1 · База", hint: "A1–A2 · самые частотные слова", words: [
"person|человек","people|люди","man|мужчина","woman|женщина","child|ребёнок","boy|мальчик","girl|девочка","family|семья","mother|мать","father|отец",
"parent|родитель","brother|брат","sister|сестра","son|сын","daughter|дочь","wife|жена","husband|муж","friend|друг","neighbour|сосед","baby|младенец",
"adult|взрослый","guest|гость","name|имя","age|возраст","body|тело","head|голова","face|лицо","eye|глаз","ear|ухо","nose|нос",
"mouth|рот","tooth|зуб","hair|волосы","neck|шея","shoulder|плечо","arm|рука (от плеча)","hand|кисть руки","finger|палец","leg|нога","knee|колено",
"foot|ступня","back|спина","chest|грудь","heart|сердце","skin|кожа","bone|кость","blood|кровь","brain|мозг","stomach|живот, желудок","muscle|мышца",
"house|дом (здание)","home|дом (родной)","room|комната","kitchen|кухня","bedroom|спальня","bathroom|ванная","door|дверь","window|окно","wall|стена","floor|пол; этаж",
"ceiling|потолок","roof|крыша","table|стол","chair|стул","bed|кровать","sofa|диван","lamp|лампа","mirror|зеркало","shelf|полка","key|ключ",
"lock|замок","garden|сад","yard|двор","stairs|лестница","cup|чашка","glass|стакан","plate|тарелка","bowl|миска","spoon|ложка","fork|вилка",
"knife|нож","bottle|бутылка","pan|сковорода","towel|полотенце","soap|мыло","brush|щётка","food|еда","bread|хлеб","meat|мясо","chicken|курица",
"fish|рыба","egg|яйцо","milk|молоко","cheese|сыр","butter|масло (сливочное)","rice|рис","potato|картофель","tomato|помидор","onion|лук","carrot|морковь",
"apple|яблоко","banana|банан","orange|апельсин","lemon|лимон","berry|ягода","nut|орех","sugar|сахар","salt|соль","pepper|перец","oil|масло (растительное)",
"soup|суп","salad|салат","cake|торт","breakfast|завтрак","lunch|обед","dinner|ужин","meal|приём пищи","water|вода","tea|чай","coffee|кофе",
"juice|сок","clothes|одежда","shirt|рубашка","trousers|брюки","jeans|джинсы","dress|платье","skirt|юбка","coat|пальто","jacket|куртка","shoe|ботинок",
"boot|сапог","sock|носок","hat|шапка","glove|перчатка","scarf|шарф","belt|ремень","pocket|карман","button|пуговица; кнопка","size|размер","time|время",
"day|день","night|ночь","morning|утро","evening|вечер","week|неделя","month|месяц","year|год","hour|час","minute|минута","second|секунда",
"today|сегодня","tomorrow|завтра","yesterday|вчера","now|сейчас","later|позже","early|рано","late|поздно","soon|скоро","always|всегда","never|никогда",
"often|часто","sometimes|иногда","usually|обычно","again|снова","still|всё ещё","already|уже","ago|тому назад","sun|солнце","moon|луна","star|звезда",
"sky|небо","cloud|облако","rain|дождь","snow|снег","wind|ветер","storm|буря","ice|лёд","fire|огонь","air|воздух","earth|земля",
"ground|земля (поверхность)","tree|дерево","leaf|лист","flower|цветок","grass|трава","forest|лес","mountain|гора","hill|холм","river|река","lake|озеро",
"sea|море","ocean|океан","beach|пляж","island|остров","field|поле","stone|камень","sand|песок","animal|животное","dog|собака","cat|кошка",
"bird|птица","horse|лошадь","cow|корова","insect|насекомое","city|город","town|городок","village|деревня","street|улица","road|дорога","bridge|мост",
"shop|магазин","market|рынок","bank|банк","school|школа","hospital|больница","park|парк","station|станция","airport|аэропорт","hotel|отель","restaurant|ресторан",
"library|библиотека","museum|музей","office|офис","factory|завод","farm|ферма","building|здание","car|машина","bus|автобус","train|поезд","plane|самолёт",
"bike|велосипед","boat|лодка","ship|корабль","ticket|билет","driver|водитель","trip|поездка","go|идти, ехать","come|приходить","get|получать","make|делать",
"take|брать","give|давать","put|класть","say|сказать","tell|рассказать","ask|спрашивать","answer|отвечать","speak|говорить","talk|разговаривать","know|знать",
"think|думать","want|хотеть","need|нуждаться","like|нравиться","love|любить","hate|ненавидеть","see|видеть","look|смотреть","watch|наблюдать","hear|слышать",
"listen|слушать","feel|чувствовать","eat|есть","drink|пить","sleep|спать","wake|просыпаться","walk|ходить пешком","run|бежать","jump|прыгать","sit|сидеть",
"stand|стоять","open|открывать","close|закрывать","start|начинать","stop|останавливать","finish|заканчивать","begin|начинать","work|работать","play|играть","read|читать",
"write|писать","learn|учить","teach|преподавать","study|изучать","buy|покупать","sell|продавать","pay|платить","cost|стоить","help|помогать","live|жить",
"die|умирать","meet|встречать","find|находить","lose|терять","win|выигрывать","keep|хранить","hold|держать","carry|нести","bring|приносить","send|отправлять",
"wait|ждать","try|пытаться","use|использовать","wash|мыть","clean|чистить","cook|готовить","drive|водить","fly|летать","swim|плавать","sing|петь",
"dance|танцевать","laugh|смеяться","cry|плакать","smile|улыбаться","call|звонить; звать","visit|посещать","travel|путешествовать","move|двигать(ся)","change|менять","build|строить",
"break|ломать","fix|чинить","cut|резать","wear|носить (одежду)","become|становиться","remember|помнить","forget|забывать","understand|понимать","explain|объяснять","choose|выбирать",
"decide|решать","believe|верить","hope|надеяться","show|показывать","happen|случаться","follow|следовать","turn|поворачивать","leave|уходить; оставлять","stay|оставаться","return|возвращаться",
"good|хороший","bad|плохой","big|большой","small|маленький","large|крупный","long|длинный","short|короткий","tall|высокий (о человеке)","high|высокий","low|низкий",
"wide|широкий","narrow|узкий","thick|толстый","thin|тонкий","heavy|тяжёлый","light|лёгкий; светлый","fast|быстрый","slow|медленный","hot|горячий","cold|холодный",
"warm|тёплый","cool|прохладный","wet|мокрый","dry|сухой","new|новый","old|старый","young|молодой","easy|лёгкий (простой)","hard|трудный; твёрдый","difficult|сложный",
"simple|простой","strong|сильный","weak|слабый","rich|богатый","poor|бедный","happy|счастливый","sad|грустный","angry|злой","tired|уставший","hungry|голодный",
"thirsty|испытывающий жажду","sick|больной","healthy|здоровый","dirty|грязный","full|полный","empty|пустой","right|правильный; правый","wrong|неправильный","true|верный","false|ложный",
"same|тот же","different|другой","important|важный","interesting|интересный","boring|скучный","beautiful|красивый","ugly|уродливый","nice|приятный","kind|добрый; вид","funny|смешной",
"serious|серьёзный","quiet|тихий","loud|громкий","dark|тёмный","bright|яркий","deep|глубокий","safe|безопасный","dangerous|опасный","free|свободный; бесплатный","busy|занятой",
"ready|готовый","sure|уверенный","real|настоящий","possible|возможный","cheap|дешёвый","expensive|дорогой","near|близкий","far|далёкий","colour|цвет","red|красный",
"blue|синий","green|зелёный","yellow|жёлтый","black|чёрный","white|белый","grey|серый","brown|коричневый","pink|розовый","purple|фиолетовый","number|число",
"many|много (счёт.)","much|много (несчёт.)","few|мало (счёт.)","more|больше","less|меньше","most|большинство","all|все, всё","some|некоторые","any|любой","every|каждый",
"each|каждый (из)","both|оба","half|половина","part|часть","piece|кусок","whole|целый","enough|достаточно","several|несколько","other|другой","another|ещё один"
]},
{ name: "Уровень 2 · Повседневный", hint: "A2–B1 · быт, работа, общение", words: [
"job|работа (должность)","career|карьера","company|компания","business|бизнес","manager|руководитель","boss|начальник","employee|сотрудник","colleague|коллега","team|команда","meeting|встреча, совещание",
"project|проект","task|задача","deadline|крайний срок","salary|зарплата","contract|договор","interview|собеседование","experience|опыт","skill|навык","training|обучение","report|отчёт",
"customer|клиент","client|заказчик","service|услуга","product|продукт","price|цена","discount|скидка","bill|счёт","receipt|чек","cash|наличные","card|карта",
"account|счёт (в банке)","budget|бюджет","profit|прибыль","loss|убыток","tax|налог","debt|долг","loan|кредит","invest|вкладывать","save|копить; спасать","spend|тратить",
"earn|зарабатывать","afford|позволить себе","owe|быть должным","borrow|занимать","lend|одалживать","rent|арендовать","own|владеть; собственный","share|делиться; доля","order|заказ; порядок","deliver|доставлять",
"idea|идея","plan|план","goal|цель","result|результат","reason|причина","problem|проблема","solution|решение","question|вопрос","mistake|ошибка","chance|шанс",
"choice|выбор","effort|усилие","habit|привычка","progress|прогресс","success|успех","failure|неудача","risk|риск","danger|опасность","safety|безопасность","rule|правило",
"law|закон","entitlement|право","duty|обязанность","freedom|свобода","power|власть; сила","control|контроль","support|поддержка","advice|совет","opinion|мнение","fact|факт",
"truth|правда","lie|ложь; лежать","secret|секрет","news|новости","story|история","message|сообщение","letter|письмо; буква","word|слово","sentence|предложение","language|язык",
"meaning|значение","example|пример","detail|деталь","list|список","note|заметка","page|страница","book|книга","paper|бумага; статья","picture|картинка","photo|фотография",
"film|фильм","song|песня","music|музыка","art|искусство","game|игра","sport|спорт","coach|тренер","exercise|упражнение","health|здоровье","medicine|лекарство",
"doctor|врач","nurse|медсестра","patient|пациент","pain|боль","injury|травма","treatment|лечение","weight|вес","height|рост","strength|сила","speed|скорость",
"distance|расстояние","direction|направление","level|уровень","step|шаг","line|линия","circle|круг","square|квадрат","shape|форма","edge|край","side|сторона",
"top|верх","bottom|низ","middle|середина","centre|центр","corner|угол","front|перед","beyond|за пределами","inside|внутри","outside|снаружи","between|между",
"above|над","below|под","behind|позади","beside|рядом с","across|через","along|вдоль","around|вокруг","through|сквозь","towards|по направлению к","against|против",
"during|во время","until|до тех пор пока","since|с тех пор как","while|пока","before|до","after|после","instead|вместо","besides|кроме того","although|хотя","however|однако",
"therefore|поэтому","because|потому что","unless|если не","whether|ли","perhaps|возможно","probably|вероятно","certainly|конечно","actually|на самом деле","especially|особенно","exactly|точно",
"almost|почти","nearly|почти","hardly|едва","rather|скорее; довольно","quite|довольно","really|действительно","simply|просто","clearly|ясно","suddenly|внезапно","finally|наконец",
"immediately|немедленно","recently|недавно","currently|в настоящее время","eventually|в конце концов","meanwhile|тем временем","anyway|в любом случае","otherwise|иначе","moreover|более того","indeed|действительно","apparently|по-видимому",
"agree|соглашаться","disagree|не соглашаться","argue|спорить","discuss|обсуждать","suggest|предлагать","offer|предлагать","accept|принимать","refuse|отказываться","allow|разрешать","forbid|запрещать",
"promise|обещать","admit|признавать","deny|отрицать","complain|жаловаться","apologise|извиняться","thank|благодарить","invite|приглашать","introduce|представлять","recommend|рекомендовать","warn|предупреждать",
"describe|описывать","compare|сравнивать","mention|упоминать","repeat|повторять","translate|переводить","pronounce|произносить","spell|писать по буквам","count|считать","measure|измерять","weigh|весить",
"check|проверять","test|проверять, тест","prove|доказывать","guess|догадываться","imagine|представлять","consider|рассматривать","expect|ожидать","prefer|предпочитать","mind|возражать; разум","care|заботиться",
"worry|волноваться","fear|бояться","enjoy|наслаждаться","relax|расслабляться","rest|отдыхать","practise|практиковать","improve|улучшать","develop|развивать","create|создавать","design|проектировать",
"produce|производить","repair|ремонтировать","destroy|разрушать","damage|повреждать","protect|защищать","prevent|предотвращать","avoid|избегать","solve|решать","manage|управлять; справляться","organise|организовывать",
"prepare|готовить(ся)","arrange|устраивать","continue|продолжать","complete|завершать","achieve|достигать","succeed|преуспевать","fail|терпеть неудачу","attempt|пытаться","uphold|отстаивать","reduce|сокращать",
"increase|увеличивать","grow|расти","fall|падать","rise|подниматься","drop|ронять; падение","raise|поднимать","add|добавлять","remove|убирать","replace|заменять","connect|соединять",
"separate|разделять","join|присоединяться","collect|собирать","gather|собирать(ся)","spread|распространять","fill|наполнять","cover|покрывать","hide|прятать","reveal|раскрывать","discover|обнаруживать",
"search|искать","seek|искать","notice|замечать","observe|наблюдать","recognise|узнавать","realise|осознавать","doubt|сомневаться","trust|доверять","depend|зависеть","belong|принадлежать",
"contain|содержать","include|включать","exclude|исключать","provide|предоставлять","supply|снабжать","require|требовать","deserve|заслуживать","warrant|оправдывать, требовать","matter|иметь значение","affect|влиять на",
"influence|влиять; влияние","cause|вызывать; причина","effect|эффект","benefit|польза","advantage|преимущество","disadvantage|недостаток","difference|разница","similar|похожий","opposite|противоположный","equal|равный",
"average|средний","total|общий","amount|количество","quantity|количество","quality|качество","value|ценность","worth|стоящий","common|обычный, общий","rare|редкий","usual|обычный",
"normal|нормальный","strange|странный","special|особый","general|общий","particular|конкретный","specific|конкретный","exact|точный","approximate|приблизительный","clear|ясный","obvious|очевидный",
"confusing|запутанный","complex|сложный","basic|базовый","main|главный","major|основной","minor|второстепенный","extra|дополнительный","spare|запасной","available|доступный","necessary|необходимый",
"useful|полезный","useless|бесполезный","helpful|полезный","harmful|вредный","perfect|идеальный","excellent|отличный","terrible|ужасный","awful|ужасный","amazing|потрясающий","wonderful|чудесный",
"comfortable|удобный","uncomfortable|неудобный","convenient|удобный","polite|вежливый","rude|грубый","honest|честный","fair|справедливый","selfish|эгоистичный","generous|щедрый","brave|храбрый",
"confident|уверенный","shy|застенчивый","tolerant|терпимый","lazy|ленивый","hard-working|трудолюбивый","clever|умный","stupid|глупый","wise|мудрый","crazy|сумасшедший","calm|спокойный",
"nervous|нервный","excited|взволнованный","bored|скучающий","surprised|удивлённый","worried|обеспокоенный","disappointed|разочарованный","proud|гордый","ashamed|пристыжённый","jealous|ревнивый","lonely|одинокий"
]},
{ name: "Уровень 3 · Средний", hint: "B1 · абстрактные понятия, оттенки", words: [
"ability|способность","access|доступ","achievement|достижение","activity|деятельность","addition|добавление","adjustment|корректировка","agreement|соглашение","aim|цель","alternative|альтернатива","analysis|анализ",
"announcement|объявление","appearance|внешность","application|заявление; приложение","approach|подход","approval|одобрение","argument|аргумент; спор","arrangement|договорённость","aspect|аспект","assistance|помощь","assumption|предположение",
"atmosphere|атмосфера","endeavour|начинание","attention|внимание","attitude|отношение","audience|аудитория","authority|власть","availability|доступность","awareness|осведомлённость","background|фон; опыт","balance|баланс",
"barrier|барьер","behaviour|поведение","belief|убеждение","boundary|граница","capacity|вместимость","category|категория","challenge|вызов","character|характер","circumstance|обстоятельство","claim|утверждение",
"comment|комментарий","commitment|обязательство","communication|общение","community|сообщество","competition|соревнование","complaint|жалоба","concept|концепция","concern|беспокойство","conclusion|вывод","condition|условие",
"confidence|уверенность","conflict|конфликт","confusion|путаница","connection|связь","consequence|последствие","consideration|соображение","consistency|последовательность","content|содержание","context|контекст","contribution|вклад",
"conversation|разговор","cooperation|сотрудничество","criticism|критика","culture|культура","curiosity|любопытство","harm|вред","decision|решение","decline|спад; отказываться","definition|определение","degree|степень",
"delay|задержка","demand|спрос; требовать","department|отдел","dependence|зависимость","description|описание","desire|желание","development|развитие","device|устройство","disappointment|разочарование","discipline|дисциплина",
"discussion|обсуждение","disease|болезнь","distribution|распределение","division|разделение","document|документ","uncertainty|неопределённость","burden|бремя","economy|экономика","education|образование","emotion|эмоция",
"emphasis|акцент","employment|занятость","encouragement|поддержка","energy|энергия","engagement|вовлечённость","enthusiasm|энтузиазм","environment|окружающая среда","equipment|оборудование","error|ошибка","estimate|оценка",
"evidence|доказательство","exception|исключение","exchange|обмен","excitement|волнение","existence|существование","expectation|ожидание","expense|расход","explanation|объяснение","expression|выражение","extent|степень",
"facility|объект, помещение","factor|фактор","feature|особенность","feedback|обратная связь","figure|цифра; фигура","flexibility|гибкость","focus|фокус","force|сила","form|форма","foundation|основа",
"frame|рамка","frequency|частота","function|функция","funding|финансирование","gap|разрыв","generation|поколение","government|правительство","growth|рост","guarantee|гарантия","guidance|руководство",
"honesty|честность","identity|личность","impact|воздействие","implementation|внедрение","importance|важность","impression|впечатление","improvement|улучшение","incident|происшествие","income|доход","indication|признак",
"industry|отрасль","information|информация","initiative|инициатива","wound|рана","innovation|инновация","insight|понимание","inspection|проверка","instance|случай","instruction|инструкция","instrument|инструмент",
"intention|намерение","interaction|взаимодействие","interest|интерес","interpretation|толкование","introduction|введение","investment|инвестиция","involvement|участие","issue|вопрос, проблема","judgement|суждение","justice|справедливость",
"knowledge|знание","lack|нехватка","leadership|лидерство","limit|предел","link|связь","location|расположение","maintenance|обслуживание","majority|большинство","management|управление","material|материал",
"measurement|измерение","method|метод","minority|меньшинство","mixture|смесь","moment|момент","motion|движение","motivation|мотивация","movement|движение","nature|природа","necessity|необходимость",
"negotiation|переговоры","network|сеть","objective|цель","obligation|обязательство","observation|наблюдение","occasion|случай, повод","operation|операция","opportunity|возможность","option|вариант","outcome|результат",
"output|выход, продукция","ownership|владение","participation|участие","pattern|закономерность","peace|мир","performance|производительность","period|период","permission|разрешение","perspective|перспектива","phase|фаза",
"phenomenon|явление","policy|политика (курс)","population|население","position|позиция","potential|потенциал","practice|практика","precision|точность","preference|предпочтение","pressure|давление","principle|принцип",
"priority|приоритет","procedure|процедура","process|процесс","profession|профессия","proof|доказательство","property|собственность; свойство","proportion|доля","proposal|предложение","protection|защита","purpose|цель",
"benchmark|эталон","range|диапазон","rate|ставка, темп","reaction|реакция","reality|реальность","recognition|признание","recovery|восстановление","reduction|сокращение","reference|ссылка","reflection|отражение",
"relationship|отношения","release|выпуск; освобождать","relief|облегчение","reputation|репутация","request|запрос","research|исследование","resistance|сопротивление","resource|ресурс","respect|уважение","response|ответ",
"responsibility|ответственность","restriction|ограничение","reward|награда","routine|распорядок","satisfaction|удовлетворение","scale|масштаб","scene|сцена","scope|охват","section|раздел","security|безопасность",
"selection|выбор","sense|чувство; смысл","sequence|последовательность","series|серия","session|сессия, занятие","setting|обстановка","shortage|нехватка","signal|сигнал","significance|значимость","similarity|сходство",
"situation|ситуация","society|общество","source|источник","stability|стабильность","stage|этап","standard|стандарт","statement|заявление","status|статус","strategy|стратегия","stress|стресс",
"structure|структура","struggle|борьба","substance|вещество","suggestion|предложение","summary|краткое изложение","provision|обеспечение","surface|поверхность","surprise|сюрприз","survival|выживание","symbol|символ",
"system|система","target|цель","technique|техника","technology|технология","tendency|тенденция","tension|напряжение","term|термин; срок","theory|теория","threat|угроза","tool|инструмент",
"topic|тема","trace|след","tradition|традиция","transfer|перевод","transition|переход","nurture|взращивать","trend|тенденция","trial|испытание","loyalty|верность","understanding|понимание",
"unit|единица","update|обновление","urgency|срочность","variety|разнообразие","version|версия","victory|победа","view|вид; взгляд","violence|насилие","vision|видение","volume|объём",
"warning|предупреждение","waste|отходы; тратить впустую","wealth|богатство","welfare|благосостояние","willingness|готовность","wisdom|мудрость","witness|свидетель","wonder|удивляться; чудо","workload|нагрузка","merit|достоинство",
"accurate|точный","adequate|достаточный","aggressive|агрессивный","ancient|древний","annual|ежегодный","anxious|тревожный","appropriate|подходящий","artificial|искусственный","aware|осведомлённый","brief|краткий",
"broad|широкий","capable|способный","careful|осторожный","cautious|осмотрительный","complicated|сложный","constant|постоянный","convinced|убеждённый","crucial|решающий","curious|любопытный","current|текущий",
"decent|приличный","delicate|хрупкий","dense|плотный","desperate|отчаянный","detailed|подробный","distinct|отчётливый","diverse|разнообразный","efficient|эффективный","eager|стремящийся","elegant|элегантный",
"essential|существенный","evident|очевидный","extreme|крайний","familiar|знакомый","flexible|гибкий","formal|формальный","fragile|хрупкий","frequent|частый","gentle|мягкий","genuine|подлинный",
"gradual|постепенный","grateful|благодарный","guilty|виновный","harsh|суровый","hidden|скрытый","huge|огромный","humble|скромный","ideal|идеальный","immediate|немедленный","independent|независимый",
"inevitable|неизбежный","initial|первоначальный","intense|интенсивный","internal|внутренний","legal|законный","likely|вероятный","loose|свободный","mature|зрелый","mild|мягкий","modest|скромный",
"mutual|взаимный","neutral|нейтральный","apparent|очевидный","occasional|случайный","ongoing|продолжающийся","permanent|постоянный","persistent|настойчивый","precise|точный","previous|предыдущий","primary|первичный",
"proper|надлежащий","rapid|быстрый","reasonable|разумный","relevant|уместный","reliable|надёжный","reluctant|неохотный","remarkable|замечательный","responsible|ответственный","rough|грубый; примерный","sensitive|чувствительный",
"severe|тяжёлый, суровый","sharp|острый","significant|значительный","smooth|гладкий","solid|твёрдый","steady|устойчивый","stiff|жёсткий","strict|строгий","subtle|тонкий","sufficient|достаточный",
"suitable|подходящий","temporary|временный","tight|тугой, тесный","tough|жёсткий, трудный","typical|типичный","unique|уникальный","urgent|срочный","vague|расплывчатый","valuable|ценный","various|различный",
"visible|видимый","vital|жизненно важный","voluntary|добровольный","vulnerable|уязвимый","willing|готовый","wealthy|состоятельный","widespread|широко распространённый","worthwhile|стоящий"
]},
{ name: "Уровень 4 · Продвинутый", hint: "B2 · глаголы, фразовые глаголы, выражения", words: [
"accomplish|совершать, достигать","accumulate|накапливать","acknowledge|признавать","acquire|приобретать","adapt|адаптировать(ся)","address|обращаться к; решать","adjust|настраивать","advocate|отстаивать","allocate|распределять","alter|изменять",
"anticipate|предвидеть","apply|применять; подавать заявку","appreciate|ценить","approve|одобрять","arise|возникать","assemble|собирать","assert|утверждать","assess|оценивать","assign|назначать","assume|предполагать",
"assure|заверять","attach|прикреплять","attain|достигать","attribute|приписывать","authorise|уполномочивать","banish|изгонять","bear|выносить, терпеть","blame|винить","boost|повышать","broaden|расширять",
"calculate|вычислять","capture|захватывать","cease|прекращать","rebut|опровергать","clarify|прояснять","classify|классифицировать","coincide|совпадать","collapse|рушиться","combine|объединять","commit|совершать; обязаться",
"compensate|компенсировать","compete|конкурировать","compile|составлять","comply|соблюдать","compose|составлять","comprehend|постигать","compromise|идти на компромисс","conceal|скрывать","concede|уступать","conduct|проводить",
"confirm|подтверждать","confront|противостоять","consent|соглашаться","conserve|сохранять","consist|состоять","constitute|составлять","construct|конструировать","consult|консультироваться","consume|потреблять","contradict|противоречить",
"contribute|вносить вклад","convert|преобразовывать","convey|передавать","convince|убеждать","coordinate|координировать","correspond|соответствовать","criticise|критиковать","cultivate|развивать, взращивать","deceive|обманывать","declare|заявлять",
"dedicate|посвящать","deduce|выводить (заключение)","defend|защищать","define|определять","delegate|делегировать","demonstrate|демонстрировать","depict|изображать","derive|извлекать, происходить","designate|обозначать","detect|обнаруживать",
"determine|определять","devote|посвящать","diminish|уменьшать(ся)","disclose|раскрывать","dismiss|отклонять; увольнять","displace|вытеснять","dispose|избавляться","dispute|оспаривать","distinguish|различать","distract|отвлекать",
"distribute|распределять","diverge|расходиться","dominate|доминировать","eliminate|устранять","embrace|принимать; обнимать","emerge|появляться","emphasise|подчёркивать","enable|позволять","enclose|прилагать, окружать","encounter|сталкиваться с",
"endure|выдерживать","enforce|обеспечивать соблюдение","engage|вовлекать","enhance|улучшать","ensure|обеспечивать","entail|влечь за собой","establish|учреждать","appraise|оценивать (стоимость)","evaluate|оценивать","evolve|развиваться",
"exaggerate|преувеличивать","examine|изучать","exceed|превышать","bypass|обходить","execute|выполнять","exhibit|демонстрировать","expand|расширять","exploit|использовать, эксплуатировать","explore|исследовать","expose|подвергать; разоблачать",
"extend|продлевать, расширять","extract|извлекать","facilitate|облегчать","fluctuate|колебаться","forecast|прогнозировать","formulate|формулировать","foster|способствовать","fulfil|выполнять","generate|производить","govern|управлять",
"grasp|схватывать; понимать","vouch|ручаться","hesitate|колебаться","highlight|выделять","hinder|мешать","identify|определять","ignore|игнорировать","illustrate|иллюстрировать","implement|внедрять","imply|подразумевать",
"impose|навязывать","incorporate|включать","indicate|указывать","induce|побуждать","infer|делать вывод","inhibit|подавлять","initiate|инициировать","innovate|внедрять новшества","inquire|осведомляться","insist|настаивать",
"inspect|проверять","inspire|вдохновлять","install|устанавливать","integrate|интегрировать","interpret|толковать","intervene|вмешиваться","invoke|вызывать, ссылаться","isolate|изолировать","justify|оправдывать","launch|запускать",
"maintain|поддерживать","manipulate|манипулировать","maximise|максимизировать","mediate|посредничать","minimise|минимизировать","modify|изменять","monitor|отслеживать","navigate|ориентироваться","neglect|пренебрегать","negotiate|вести переговоры",
"nominate|выдвигать","obtain|получать","occupy|занимать","occur|происходить","omit|пропускать","operate|работать, управлять","oppose|противостоять","optimise|оптимизировать","originate|происходить","overcome|преодолевать",
"overlap|перекрываться","overlook|упускать из виду","participate|участвовать","perceive|воспринимать","persist|упорствовать","persuade|убеждать","pledge|обязываться","portray|изображать","possess|обладать","postpone|откладывать",
"precede|предшествовать","predict|предсказывать","preserve|сохранять","presume|полагать","prioritise|расставлять приоритеты","proceed|продолжать","prohibit|запрещать","envision|представлять себе","promote|продвигать","prompt|побуждать",
"pursue|преследовать (цель)","qualify|квалифицировать(ся)","quote|цитировать","react|реагировать","reassure|успокаивать","rebuild|перестраивать","recall|вспоминать","reckon|полагать, считать","reconcile|примирять","recover|восстанавливаться",
"refine|совершенствовать","reflect|отражать; размышлять","refrain|воздерживаться","regard|считать, расценивать","register|регистрировать","regulate|регулировать","reinforce|укреплять","reject|отвергать","relate|соотносить","relieve|облегчать",
"rely|полагаться","remark|замечать","reproduce|воспроизводить","resemble|напоминать","reserve|резервировать","reside|проживать","resolve|разрешать (проблему)","restore|восстанавливать","restrain|сдерживать","restrict|ограничивать",
"retain|сохранять","retrieve|извлекать","unveil|обнародовать","revise|пересматривать","sacrifice|жертвовать","satisfy|удовлетворять","scatter|разбрасывать","secure|обеспечивать; надёжный","simulate|имитировать","specify|указывать точно",
"stimulate|стимулировать","strengthen|укреплять","strive|стремиться","submit|подавать; подчиняться","subsequent|последующий","substitute|заменять","summarise|резюмировать","surpass|превосходить","survive|выживать","sustain|поддерживать",
"tackle|решать (проблему)","terminate|прекращать","thrive|процветать","tolerate|терпеть","transform|преобразовывать","transmit|передавать","undergo|претерпевать","undermine|подрывать","undertake|предпринимать","unify|объединять",
"utilise|использовать","validate|подтверждать","vanish|исчезать","vary|варьироваться","verify|проверять","violate|нарушать","withdraw|изымать; отступать","withstand|выдерживать","testify|свидетельствовать","yield|уступать; давать урожай",
"give up|бросать, сдаваться","keep up|поддерживать темп","work out|тренироваться; получаться","figure out|разобраться","find out|выяснить","carry out|выполнять","point out|указать на","turn out|оказаться","bring up|поднимать (тему)","come up with|придумать",
"put off|откладывать","put up with|мириться с","look forward to|с нетерпением ждать","look after|заботиться о","look into|изучать вопрос","run out of|закончиться (о запасе)","get rid of|избавиться от","catch up|нагнать","set up|настроить, создать","take over|принять управление",
"take on|браться за","hold on|подождать","break down|сломаться","break up|расставаться","cut down on|сократить","go through|пройти через","get along with|ладить с","stand out|выделяться","show up|появиться","end up|в итоге оказаться",
"make up for|компенсировать","pick up|подобрать; научиться","drop off|подвезти; заснуть","call off|отменить","turn down|отклонить","turn up|появиться; прибавить","back up|поддержать; резервировать","sort out|уладить","work on|работать над","rely on|полагаться на",
"focus on|сосредоточиться на","deal with|иметь дело с","result in|приводить к","account for|объяснять; составлять","consist of|состоять из","apply for|подавать заявку на","insist on|настаивать на","object to|возражать против","benefit from|извлекать пользу из","refer to|ссылаться на",
"on purpose|намеренно","at least|по крайней мере","at last|наконец","in advance|заранее","in charge of|ответственный за","in terms of|с точки зрения","as a result|в результате","for the sake of|ради","on behalf of|от имени","by means of|посредством",
"in spite of|несмотря на","due to|из-за","as long as|при условии что","no longer|больше не","as well as|а также","rather than|а не","let alone|не говоря уже о","take into account|принять во внимание","make sense|иметь смысл","keep in mind|иметь в виду",
"make a difference|иметь значение","take advantage of|воспользоваться","pay attention to|обращать внимание на","get used to|привыкать к","be about to|собираться (вот-вот)","be worth|стоить того","come across|наткнуться на","bear in mind|помнить","on the whole|в целом","to some extent|в некоторой степени"
]}
];
